import type { Spell } from '@/types';
import { SPELL_TEMPLATES } from './templates';

/** `energyCost` and `unlockLevel` scale roughly with `difficulty` so the early game (novice) is always fully playable. */
export const BUILTIN_SPELLS: Spell[] = [
  {
    id: 'ignis',
    name: 'Ignis',
    element: 'fire',
    difficulty: 'novice',
    description: 'Uma explosão de fogo que irradia calor e brasas ao redor do alvo.',
    lore: 'O primeiro feitiço ensinado a todo aprendiz: um triângulo ascendente, símbolo da chama que sempre busca o céu, cortado por uma linha que representa o combustível que a alimenta.',
    energyCost: 18,
    color: '#ff6a3d',
    template: SPELL_TEMPLATES.ignis!,
    particlePresetId: 'fire',
    soundId: 'fire',
    unlockLevel: 0,
  },
  {
    id: 'aqua',
    name: 'Aqua',
    element: 'water',
    difficulty: 'novice',
    description: 'Uma corrente de água que flui e ondula, refratando a luz ao redor.',
    lore: 'A espiral representa o eterno ciclo das marés; sua cauda descendente é a chuva que retorna à terra.',
    energyCost: 16,
    color: '#3da9ff',
    template: SPELL_TEMPLATES.aqua!,
    particlePresetId: 'water',
    soundId: 'water',
    unlockLevel: 0,
  },
  {
    id: 'ventus',
    name: 'Ventus',
    element: 'air',
    difficulty: 'adept',
    description: 'Uma rajada de vento que dispersa folhas e poeira, distorcendo o ar.',
    lore: 'Três curvas paralelas — o vento nunca sopra sozinho, ele vem em ondas.',
    energyCost: 20,
    color: '#8be9c8',
    template: SPELL_TEMPLATES.ventus!,
    particlePresetId: 'dust',
    soundId: 'air',
    unlockLevel: 0,
  },
  {
    id: 'terra',
    name: 'Terra',
    element: 'earth',
    difficulty: 'adept',
    description: 'Pedras emergem do solo com um impacto que treme a área.',
    lore: 'O quadrado é a base de toda construção; o ponto central, o núcleo imóvel da montanha.',
    energyCost: 22,
    color: '#c98a4b',
    template: SPELL_TEMPLATES.terra!,
    particlePresetId: 'dust',
    soundId: 'earth',
    unlockLevel: 0,
  },
  {
    id: 'lux',
    name: 'Lux',
    element: 'light',
    difficulty: 'novice',
    description: 'Um clarão dourado com raios e brilho residual (lens flare).',
    lore: 'A estrela de cinco pontas é o símbolo mais antigo da luz guiando os perdidos.',
    energyCost: 15,
    color: '#ffe27a',
    template: SPELL_TEMPLATES.lux!,
    particlePresetId: 'energy',
    soundId: 'light',
    unlockLevel: 0,
  },
  {
    id: 'umbra',
    name: 'Umbra',
    element: 'shadow',
    difficulty: 'expert',
    description: 'Fumaça escura consome a luz ao redor, absorvendo partículas para o centro.',
    lore: 'A lua minguante invertida é o símbolo proibido — luz que se afasta de si mesma.',
    energyCost: 26,
    color: '#8b5cf6',
    template: SPELL_TEMPLATES.umbra!,
    particlePresetId: 'shadow',
    soundId: 'shadow',
    unlockLevel: 3,
  },
  {
    id: 'fulmen',
    name: 'Fulmen',
    element: 'electric',
    difficulty: 'expert',
    description: 'Descargas elétricas ramificadas cortam o ar com um estrondo.',
    lore: 'O raio é o único símbolo que a natureza desenha sozinha — os magos apenas o imitam.',
    energyCost: 28,
    color: '#f7ef4a',
    template: SPELL_TEMPLATES.fulmen!,
    particlePresetId: 'electric',
    soundId: 'electric',
    unlockLevel: 4,
  },
  {
    id: 'glacies',
    name: 'Glacies',
    element: 'ice',
    difficulty: 'master',
    description: 'Cristais de gelo congelam gradualmente a área com névoa fria.',
    lore: 'Nenhum floco de neve é igual, mas todos guardam a mesma simetria de seis pontas.',
    energyCost: 30,
    color: '#bff6ff',
    template: SPELL_TEMPLATES.glacies!,
    particlePresetId: 'snow',
    soundId: 'ice',
    unlockLevel: 5,
  },
  {
    id: 'vita',
    name: 'Vita',
    element: 'nature',
    difficulty: 'adept',
    description: 'Plantas brotam do solo e vaga-lumes de energia verde restauram forças.',
    lore: 'A folha com sua nervura central é o desenho mais simples que a natureza repete infinitamente.',
    energyCost: 20,
    color: '#5fd97a',
    template: SPELL_TEMPLATES.vita!,
    particlePresetId: 'leaves',
    soundId: 'nature',
    unlockLevel: 1,
  },
  {
    id: 'aether',
    name: 'Aether',
    element: 'arcane',
    difficulty: 'master',
    description: 'Um portal se abre com distorção espacial e partículas cósmicas.',
    lore: 'O círculo com três pontos é o selo dos arquimagos: o todo, contendo a tríade do ser.',
    energyCost: 34,
    color: '#e8d5ff',
    template: SPELL_TEMPLATES.aether!,
    particlePresetId: 'energy',
    soundId: 'arcane',
    unlockLevel: 6,
  },
];

export const SPELLS_BY_ID: Record<string, Spell> = Object.fromEntries(
  BUILTIN_SPELLS.map((s) => [s.id, s]),
);
