import type { Spell, SpellElement } from '@/types';

export type OscillatorShape = 'sine' | 'square' | 'sawtooth' | 'triangle';

export interface TonePreset {
  shape: OscillatorShape;
  frequencies: number[];
  detune: number;
  attack: number;
  decay: number;
  sustain: number;
  release: number;
  filterType: BiquadFilterType;
  filterFrequency: number;
  noiseMix: number;
  noiseFilterType: BiquadFilterType;
  noiseFilterFrequency: number;
  duration: number;
}

export const ELEMENT_TONE_PRESETS: Record<SpellElement, TonePreset> = {
  fire: {
    shape: 'sawtooth',
    frequencies: [110, 165],
    detune: 8,
    attack: 0.01,
    decay: 0.25,
    sustain: 0.15,
    release: 0.35,
    filterType: 'lowpass',
    filterFrequency: 900,
    noiseMix: 0.35,
    noiseFilterType: 'lowpass',
    noiseFilterFrequency: 1400,
    duration: 0.6,
  },
  water: {
    shape: 'sine',
    frequencies: [320, 480, 640],
    detune: 6,
    attack: 0.02,
    decay: 0.3,
    sustain: 0.2,
    release: 0.5,
    filterType: 'bandpass',
    filterFrequency: 1200,
    noiseMix: 0.25,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 1800,
    duration: 0.65,
  },
  air: {
    shape: 'triangle',
    frequencies: [220, 330],
    detune: 14,
    attack: 0.05,
    decay: 0.2,
    sustain: 0.3,
    release: 0.6,
    filterType: 'bandpass',
    filterFrequency: 2000,
    noiseMix: 0.5,
    noiseFilterType: 'bandpass',
    noiseFilterFrequency: 2400,
    duration: 0.7,
  },
  earth: {
    shape: 'square',
    frequencies: [70, 105],
    detune: 4,
    attack: 0.005,
    decay: 0.4,
    sustain: 0.1,
    release: 0.3,
    filterType: 'lowpass',
    filterFrequency: 500,
    noiseMix: 0.4,
    noiseFilterType: 'lowpass',
    noiseFilterFrequency: 700,
    duration: 0.55,
  },
  light: {
    shape: 'triangle',
    frequencies: [660, 880, 1320],
    detune: 5,
    attack: 0.005,
    decay: 0.35,
    sustain: 0.25,
    release: 0.7,
    filterType: 'highpass',
    filterFrequency: 300,
    noiseMix: 0.1,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 3000,
    duration: 0.75,
  },
  shadow: {
    shape: 'sawtooth',
    frequencies: [80, 84, 160],
    detune: 20,
    attack: 0.08,
    decay: 0.4,
    sustain: 0.35,
    release: 0.9,
    filterType: 'lowpass',
    filterFrequency: 450,
    noiseMix: 0.3,
    noiseFilterType: 'lowpass',
    noiseFilterFrequency: 500,
    duration: 0.95,
  },
  electric: {
    shape: 'square',
    frequencies: [440, 880],
    detune: 30,
    attack: 0.001,
    decay: 0.12,
    sustain: 0.05,
    release: 0.2,
    filterType: 'highpass',
    filterFrequency: 600,
    noiseMix: 0.6,
    noiseFilterType: 'bandpass',
    noiseFilterFrequency: 2600,
    duration: 0.4,
  },
  ice: {
    shape: 'sine',
    frequencies: [880, 1320, 1760],
    detune: 3,
    attack: 0.005,
    decay: 0.5,
    sustain: 0.15,
    release: 0.8,
    filterType: 'highpass',
    filterFrequency: 500,
    noiseMix: 0.15,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 4000,
    duration: 0.85,
  },
  nature: {
    shape: 'triangle',
    frequencies: [392, 523, 659],
    detune: 5,
    attack: 0.02,
    decay: 0.3,
    sustain: 0.25,
    release: 0.6,
    filterType: 'lowpass',
    filterFrequency: 2200,
    noiseMix: 0.1,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 2000,
    duration: 0.7,
  },
  arcane: {
    shape: 'sine',
    frequencies: [55, 110, 1760],
    detune: 10,
    attack: 0.15,
    decay: 0.4,
    sustain: 0.4,
    release: 1.1,
    filterType: 'lowpass',
    filterFrequency: 1600,
    noiseMix: 0.2,
    noiseFilterType: 'bandpass',
    noiseFilterFrequency: 1800,
    duration: 1.1,
  },
};

/** Resolves which of the ten sound profiles a spell should play — its own `soundId` when valid, else its element. */
export function soundElementFor(spell: Spell): SpellElement {
  return spell.soundId in ELEMENT_TONE_PRESETS ? (spell.soundId as SpellElement) : spell.element;
}

export const UI_TONE_PRESETS: Record<string, TonePreset> = {
  click: {
    shape: 'triangle',
    frequencies: [520],
    detune: 0,
    attack: 0.001,
    decay: 0.06,
    sustain: 0,
    release: 0.08,
    filterType: 'highpass',
    filterFrequency: 300,
    noiseMix: 0.05,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 3000,
    duration: 0.12,
  },
  hover: {
    shape: 'sine',
    frequencies: [880],
    detune: 0,
    attack: 0.001,
    decay: 0.03,
    sustain: 0,
    release: 0.04,
    filterType: 'highpass',
    filterFrequency: 500,
    noiseMix: 0,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 3000,
    duration: 0.06,
  },
  failure: {
    shape: 'sawtooth',
    frequencies: [180, 160],
    detune: 40,
    attack: 0.01,
    decay: 0.2,
    sustain: 0.1,
    release: 0.4,
    filterType: 'lowpass',
    filterFrequency: 500,
    noiseMix: 0.4,
    noiseFilterType: 'lowpass',
    noiseFilterFrequency: 800,
    duration: 0.5,
  },
  perfect: {
    shape: 'triangle',
    frequencies: [660, 880, 1100, 1320],
    detune: 2,
    attack: 0.005,
    decay: 0.25,
    sustain: 0.3,
    release: 0.9,
    filterType: 'highpass',
    filterFrequency: 200,
    noiseMix: 0.05,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 4000,
    duration: 1,
  },
  discovery: {
    shape: 'sine',
    frequencies: [523, 659, 784, 1047],
    detune: 1,
    attack: 0.01,
    decay: 0.3,
    sustain: 0.4,
    release: 1.2,
    filterType: 'lowpass',
    filterFrequency: 4000,
    noiseMix: 0.05,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 4000,
    duration: 1.3,
  },
  charge: {
    shape: 'sine',
    frequencies: [220],
    detune: 0,
    attack: 0.4,
    decay: 0.1,
    sustain: 0.6,
    release: 0.1,
    filterType: 'lowpass',
    filterFrequency: 1200,
    noiseMix: 0.02,
    noiseFilterType: 'highpass',
    noiseFilterFrequency: 2000,
    duration: 0.5,
  },
};
